### ISSUE TITLE
[Improvment] Add fields for embeds

### ISSUE THREAD

**Issue by EL-R1** [fieu/discord.sh#53]
I was wondering if there will be a way to add fields like this example :
(Or maybe an update to implement it)

![image](https://user-images.githubusercontent.com/56195379/212098442-eb50fbc4-5a5d-41da-b44f-8ce0f82080a8.png)

**Comment by fieu** [comment]
@EL-R1 

Fields have been implemented for a while 😄 (specifically here: https://github.com/fieu/discord.sh/commit/c0928dd4d2e12140918600bdb343fca8bd8e9b49)

Check out the docs [here](https://github.com/fieu/discord.sh#---field-namevalueinline) for more information on how to use fields.
