### ISSUE TITLE
Include version number as comment in header

### ISSUE THREAD

**Issue by Querela** [fieu/discord.sh#56]
I think it would be a good idea to include the version number in the header in a comment.

A possible use-case would be that you have set up the script some time ago and now don't know which version it was or when it was done. This would then be helpful in case you want to update (which basically amounts to just downloading from the github releases but to know which version you had run is still important in case there are some breaking changes etc).

Another option might be to rename the release file to `discord-X.Y.Z.sh`.
Or introduce a `--version` CLI flag? (But the version can also be shown in the `--help` message.)

**Comment by fieu** [comment]
@Querela Good idea and a complete oversight on my part, I will add that this week. 👍
