### ISSUE TITLE
Creating Role

### ISSUE THREAD

**Issue by EL-R1** [fieu/discord.sh#61]
Is there a way to create a Role?
Or to add the feature?

**Comment by fieu** [comment]
Hello @EL-R1,

The goal of this project is to only send webhook messages via Discord, not manage a server.

You should be able to implement this easily in your own Bash script using `curl` if you'd like, but unfortunately it's not in the scope of the project.

Discord API "Add Member Role" request information: https://discord.com/developers/docs/resources/guild#add-guild-member-role
